language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - if [ $LUA = "luajit" ]; then
      sudo luarocks install ljsyscall;
    fi
  - sudo luarocks install luafilesystem --from=https://rocks.moonscript.org/dev
  - sudo luarocks install luacov-coveralls

install:
  - sudo luarocks install https://raw.github.com/moteus/lunit/moteus-skip/rockspecs/lunitx-scm.mot.skip-0.rockspec --deps-mode=none

script:
  - cd test
  - lunit.sh run.lua
  - lua -lluacov test_lfs.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
