language: c

env:
  global:
    - LUAROCKS=2.2.0-rc1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo luarocks install luafilesystem
  - if [ $LUA = "luajit" ]; then
      sudo luarocks install ljsyscall;
    fi

install:
  - sudo luarocks make rockspecs/lua-path-scm-0.rockspec

  - git clone https://github.com/moteus/luafilesystem.git luafilesystem
  - cd ./luafilesystem
  - sudo luarocks make rockspecs/luafilesystem-cvs-3.rockspec
  - cd ..
  - sudo luarocks install luacov-coveralls

  - sudo luarocks install https://raw.github.com/moteus/lunit/moteus-skip/rockspecs/lunitx-scm.mot.skip-0.rockspec --deps-mode=none

script:
  - cd test
  - lua -lpath.lfs.fs -v
  - lunit.sh run.lua
  - lua -lluacov test_lfs.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
